# Generated by Django 4.1.7 on 2023-03-17 15:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Coordenadas',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('latitude', models.CharField(max_length=10)),
                ('longitude', models.CharField(max_length=10)),
            ],
            options={
                'db_table': 'coordenadas',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Meses',
            fields=[
                ('id', models.OneToOneField(db_column='id', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='heatMap.coordenadas')),
                ('janeiro21', models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True)),
                ('fevereiro21', models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True)),
                ('marco21', models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True)),
                ('abril21', models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True)),
                ('maio21', models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True)),
                ('junho21', models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True)),
                ('julho21', models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True)),
                ('agosto21', models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True)),
                ('setembro21', models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True)),
                ('outubro21', models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True)),
                ('novembro21', models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True)),
                ('dezembro21', models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True)),
                ('janeiro22', models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True)),
            ],
            options={
                'db_table': 'meses',
                'managed': False,
            },
        ),
    ]
