# Generated by Django 4.1.7 on 2023-03-18 22:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('heatMap', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='meses',
            options={},
        ),
    ]
