# Generated by Django 4.1.7 on 2023-03-18 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('heatMap', '0003_data_alter_meses_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
